[build]
  command = "npm run build"
  publish = "dist"

# Custom Headers for .js and .jsx files
[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "public, max-age=31536000"

# Custom Headers for security best practices
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self'"

# Redirects (similar to .htaccess redirects)
[[redirects]]
  from = "/old-page"
  to = "/new-page"
  status = 301

[[redirects]]
  from = "/old-blog/*"
  to = "/new-blog/:splat"
  status = 301

[[redirects]]
  from = "/maintenance"
  to = "/maintenance.html"
  status = 302
